version: '3.9'

services:
  web:
    build: ./web
    environment:
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@db:3306/${MYSQL_DATABASE}
    ports:
      - '80:80'
    volumes:
      - ./web:/var/www/html/
    networks:
      - journals

  db:
    image: mysql:8.0.36
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - dbdata:/var/lib/mysql

    networks:
      - journals

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '81:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - journals

networks:
  journals:

volumes:
  dbdata:
